apiVersion: apps/v1
kind: Deployment
metadata:
   name: hello-app
   namespace: default
spec:
   replicas: 1
   selector:
      matchLabels:
         bb: web
   template:
      metadata:
         labels:
            bb: web
      spec:
         containers:
            - name: hello-app
              image: hello-app
              imagePullPolicy: Never